typography_spectrum: 0.4991568
color:
  brandColors:
    - '#000000'
    - '#7561B8'
    - '#27FFCA'
    - '#72FFC3'
    - '#6CD2CC'
  brandStrength: 0.915683
  lightness: 0
  saturation: 0.4974705
  rhythmicContrast: 0.4881956
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Just Good Music
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Just Good Music
description: '#justgoodmusic'
purpose: []
