name: Just Good Music
favicon: null
layout_spectrum: 0.99393
typography_spectrum: 0.4991568
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: This Is My Tag
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7561B8'
    - '#27FFCA'
    - '#72FFC3'
    - '#6CD2CC'
  brandStrength: 0.915683
  lightness: 0
  saturation: 0.4974705
  rhythmicContrast: 0.4881956
purpose: []
