purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: This Is My Tag
color:
  saturation: 0.5025295
  brandStrength: 0.915683
  lightness: 0.341484
  brandColors:
    - '#000000'
    - '#7561B8'
    - '#27FFCA'
    - '#72FFC3'
    - '#6CD2CC'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Just Good Music
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4991568
layout_spectrum: 1
